<?php 
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@// Source: pong.proto 
//   Date: 2016-02-19 01:19:20 


namespace  {

         
    class Pong extends \DrSlump\Protobuf\Message {
                                                             
        /** @var \DrSlump\Protobuf\Descriptor */
        protected static $__descriptor;
        /** @var \Closure[] */
        protected static $__extensions = array();

        public static function descriptor()
        {
            $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, '.Pong');

                        // required int32 server_log_id = 1 
            $f = new \DrSlump\Protobuf\Field();
            $f->number = 1;
            $f->name   = "server_log_id";
            $f->rule   = \DrSlump\Protobuf\Protobuf::RULE_REQUIRED;
            $f->type   = \DrSlump\Protobuf\Protobuf::TYPE_INT32;

            $descriptor->addField($f);
                        // required string key = 2 
            $f = new \DrSlump\Protobuf\Field();
            $f->number = 2;
            $f->name   = "key";
            $f->rule   = \DrSlump\Protobuf\Protobuf::RULE_REQUIRED;
            $f->type   = \DrSlump\Protobuf\Protobuf::TYPE_STRING;

            $descriptor->addField($f);
                        // required int32 player_count = 3 
            $f = new \DrSlump\Protobuf\Field();
            $f->number = 3;
            $f->name   = "player_count";
            $f->rule   = \DrSlump\Protobuf\Protobuf::RULE_REQUIRED;
            $f->type   = \DrSlump\Protobuf\Protobuf::TYPE_INT32;

            $descriptor->addField($f);
            
            foreach (self::$__extensions as $cb) {
                $descriptor->addField($cb(), true);
            }

            return $descriptor;
        }


                
        /**
         * Check if "server_log_id" has a value
         *
         * @return boolean
         */
        public function hasServerLogId()
        {
            return isset($this->server_log_id);
        }

        /**
         * Clear "server_log_id" value
         */
        public function clearServerLogId()
        {
            unset($this->server_log_id);
        }

        
        /**
         * Get "server_log_id" value
                  * @return \int                  *
         *
         */
        public function getServerLogId()
        {
                        return $this->server_log_id;
                    }

        /**
         * Set "server_log_id" value
         *
         * @param \int $value
         */
        public function setServerLogId($value)
        {
            return $this->server_log_id = $value;
        }

        
                
        /**
         * Check if "key" has a value
         *
         * @return boolean
         */
        public function hasKey()
        {
            return isset($this->key);
        }

        /**
         * Clear "key" value
         */
        public function clearKey()
        {
            unset($this->key);
        }

        
        /**
         * Get "key" value
                  * @return \string                  *
         *
         */
        public function getKey()
        {
                        return $this->key;
                    }

        /**
         * Set "key" value
         *
         * @param \string $value
         */
        public function setKey($value)
        {
            return $this->key = $value;
        }

        
                
        /**
         * Check if "player_count" has a value
         *
         * @return boolean
         */
        public function hasPlayerCount()
        {
            return isset($this->player_count);
        }

        /**
         * Clear "player_count" value
         */
        public function clearPlayerCount()
        {
            unset($this->player_count);
        }

        
        /**
         * Get "player_count" value
                  * @return \int                  *
         *
         */
        public function getPlayerCount()
        {
                        return $this->player_count;
                    }

        /**
         * Set "player_count" value
         *
         * @param \int $value
         */
        public function setPlayerCount($value)
        {
            return $this->player_count = $value;
        }
    }
}


